"""DodanieModeluRoslina

Revision ID: 33eb9b0e94d2
Revises: 
Create Date: 2025-12-02 10:31:26.595140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33eb9b0e94d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rosliny',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gatunek', sa.String(length=100), nullable=False),
    sa.Column('cena', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dostepnosc', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Rosliny')
    # ### end Alembic commands ###
